### ISSUE TITLE
Player cannot die

### ISSUE THREAD

**Issue by Vikare** [Vikare/Archon#10]
It is impossible for the player to die regardless of their current hit points as combat will continue after the player has taken lethal damage. Subsequent damage will send the player's hit points well into the negatives with no consequence in combat or exploration.

**Comment by Kexus** [comment]
Looking through the source code, it doesn't look like the program ever checks the player's health. `runCombat()` only checks the enemy health.

**Comment by Vikare** [comment]
Added checks in `run()` and `runCombat()` for player hit points at the beginning and end of their main loops respectively.
