### ISSUE TITLE
Separating game data from the application

### ISSUE THREAD

**Issue by Vikare** [Vikare/Archon#18]
The Game class currently encapsulates everything in Archon, from the GUI to the resource loaders. Ideally a top-level class called Application could serve this purpose, while Game is instead relegated to simply holding game logic and data. This means that Game data can eventually be saved without having to also save miscellaneous application utilities.

This is an essential enhancement as I feel that the game shouldn't contain any utility objects within itself. It should instead reference these externally when needed. Though use of Singletons will reduce the impact of such a change, this should be done ASAP as logic in main runs directly into Game.

**Comment by Kexus** [comment]
This seems reasonable, although perhaps not mandatory. I'll trust your judgement on issues like this.

**Comment by Vikare** [comment]
Committed to feature branch with 54674690b6c641af2af58cd972afca71046d3428 and merged into main development branch with bb26b309d5d22e0cdff5d49dea9d8e784c97e982

As of now Game isn't really referenced at all, but there's very little game logic to process, let alone data to store.

**Comment by Vikare** [comment]
Game's old functionality has been completely removed and transferred to Application as of 067900ec79e8a5708ab5f13273a7547c7692c2e8 . It is a blank slate ready to hold game logic alone.

Currently it still exists as a singleton, as I don't expect that we'll be running multiple games at once in different frames within the application. This can be discussed and changed later.
