### ISSUE TITLE
Resource folder location

### ISSUE THREAD

**Issue by Vikare** [Vikare/Archon#19]
Initial commits have the resource folder inside src. This is a pain for development because exporting the project to a runnable jar means that the resources become packed into the jar. When running this, it looks for src/resources and src no longer exists.

This was covered up with a debug boolean that needed to be switched to false on export, telling the program to search in the root directory for resources rather than inside of src.

In the game data separation branch I've moved the resources folder outside of src so that a common filepath can always be used. Is this a solution that everyone is okay with? This means that no resources will be stored inside the jar, which I honestly prefer. This also means we won't have to fiddle around with merging default resources inside the jar with external resources added by the player.

**Comment by Kexus** [comment]
This seems like a completely acceptable change to make. Since the resources folder is distributed as a zip file anyway, it may actually make things simpler since there wont be a need to worry about people extracting the resources to the wrong location, and allows other files such as a readme to be packaged.

**Comment by Vikare** [comment]
Committed to feature branch with 54674690b6c641af2af58cd972afca71046d3428 and merged into main development branch with bb26b309d5d22e0cdff5d49dea9d8e784c97e982

**Comment by Vikare** [comment]
Other development branches should merge these changes ASAP.
