### ISSUE TITLE
Standard Array is all 0's

### ISSUE THREAD

**Issue by Kexus** [Vikare/Archon#8]
Choose the "Standard Array" generation method creates an array of all 0's. A character created this way will have stats of all 0, as well as modifiers of all 0.

**Comment by Vikare** [comment]
Method referenced incorrect variable when passing values to assignScores.

    public void genStandardArray()
    {
        int[] standardArray = {15,14,13,12,10,8};
        this.assignScores(genScores);
    }
genScores is used in the other generations methods and has been changed to standardArray

    public void genStandardArray()
    {
        int[] standardArray = {15,14,13,12,10,8};
         this.assignScores(standardArray);
    }

An additional provision for an ability score of 0 or lower has also been added to genAbilityModifiers, assigning a value of -6 to the mod. This coincides with the maximum mod of 6 for an ability score of 22 or higher.
